// angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { ChatClientService, ChannelService, StreamI18nService } from 'stream-chat-angular';
import axios from 'axios';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements OnInit {
  constructor(
    private chatService: ChatClientService,
    private channelService: ChannelService,
    private streamI18nService: StreamI18nService,
  ) {
    const user = '00000000-0000-0000-0000-000000000001';

    this.chatService.init('yfea84z3npk4', user, async () => await axios.get('http://localhost:5274/Token?user=' + user).then(x => x.data));
    this.streamI18nService.setTranslation();
  }

  async ngOnInit() {
    const user = '00000000-0000-0000-0000-000000000001';
    this.channelService.init({
      type: 'messaging',
      members: { $in: [ user ] }
    });
  }
}

<div id="root">
  <stream-channel-list></stream-channel-list>
  <stream-channel>
    <stream-channel-header></stream-channel-header>
    <stream-message-list></stream-message-list>
    <stream-notification-list></stream-notification-list>
    <stream-message-input></stream-message-input>
    <stream-thread name="thread">
      <stream-message-list
        mode="thread"
      ></stream-message-list>
      <stream-message-input
        mode="thread"
      ></stream-message-input>
    </stream-thread>
  </stream-channel>
</div>

// react/src/App.js
import { Chat, Channel, ChannelList, ChannelHeader, Thread, Window, MessageList, MessageInput, } from 'stream-chat-react';
import React from 'react';
import { useSearchParams } from 'react-router-dom';
import { StreamChat } from 'stream-chat';
import axios from 'axios';
import './app.scss';

const client = new StreamChat('yfea84z3npk4');

function App() {
  const [searchParams] = useSearchParams();
  const user = searchParams.get('user');
  client.connectUser(
    {
      id: user,
      name: user,
    },
    async () => await axios.get('http://localhost:5274/Token?user=' + user).then(x => x.data),
  );

  const filters = { members: { $in: [ user ] } }

  return (
    <Chat client={client}>
    <ChannelList showChannelSearch filters={filters} />
    <Channel>
      <Window>
        <ChannelHeader />
        <MessageList />
        <MessageInput />
      </Window>
      <Thread />
    </Channel>
  </Chat>
  );
}

export default App;
